Repository linuxfoundation/easycla, pull requests merged in 2019-11, with the labels that each got.

#315 Doc update 306
  docs/cla-troubleshooting.md
  docs/contributors.md
Labels: documentation

#324 Add links to JIRA service desk product support for further EasyCLA help
  cla-backend/cla/utils.py
Labels: enhancement

#375 Added Support for OPNFV
  cla-backend/cla/models/dynamo_models.py
  cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
  cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.scss
Labels: onboarding

#377 Added Display Error for OpenCLA Button #69
  cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.html
  cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.scss
  cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.ts
Labels: 02 - Med High, Console - Corp, bug
