Repository linuxfoundation/easycla, pull requests merged in 2019-09, with the labels that each got.

#178 correct_CLA_Add_CLA_Manager
  docs/imgs/CLA-Add-CLA-Manager.png
Labels: 03 - Medium, documentation, size:X-Small

#203 GitHub Application Status Update Failure
  .circleci/config.yml
  cla-backend/cla/config.py
  cla-backend/cla/models/github_models.py
  cla-backend/cla/models/gitlab_models.py
  cla-backend/cla/test_github_models.py
Labels: 02 - Med High

#240 CLA_1054_doc_updates
  CONTRIBUTING.md
  DEV.md
  README.md
  docs/ARCHITECTURE.md
  docs/Add-Contributor-License-Agreements.md
  docs/Add-Gerrit-Instances-to-CLA-Monitoring-or-Delete-Them-From-CLA-Monitoring.md
  docs/Add-GitHub-Repositories-to-CLA-Monitoring-or-Remove-Them-From-CLA-Monitoring.md
  docs/Add-a-CLA-Group.md
  docs/Add-a-Company-to-a-Project.md
  docs/Add-or-Delete-CCLA-Managers.md
  docs/CCLA-Managers-and-CCLA-Signatories.md
  docs/CLA-Managers-and-CLA-Signatories.md
  docs/CLA-Troubleshooting.md
  docs/Contribute-to-a-Gerrit-Project.md
  docs/Contribute-to-a-GitHub-Company-Project.md
  docs/Contributors.md
  docs/EasyCLA-FAQs.md
  docs/Edit-the-Company-Name-and-Manager-Details.md
  docs/Get-Access-to-EasyCLA.md
  docs/Install-the-EasyCLA-Application.md
  docs/Manage-CLA-Group-Details.md
  docs/Project-Managers.md
  docs/Review-and-Sign-a-Corporate-CLA-by-Request.md
  docs/Sign-In-to-the-CLA-Corporate-Console.md
  docs/Sign-In-to-the-CLA-Management-Console.md
  docs/Sign-Out-of-EasyCLA.md
  docs/Sign-a-CLA-as-an-Individual-Contributor-to-GitHub.md
  docs/Sign-a-Corporate-CLA-on-Behalf-of-the-Company.md
  docs/View-Employee-Acknowledgements.md
  docs/Whitelist-Contributors.md
  docs/getting-started.md
  docs/imgs/CLA-GitHub-Branch-Add-rule.png
  docs/imgs/CLA-GitHub-Options.png
Labels: documentation
