Repository linuxfoundation/easycla, pull requests merged in 2020-10, with the labels that each got.

#1906 Completed V1 landing page UI and Redirection.
  cla-frontend-corporate-console/src/ionic/index.html
  cla-landing-page/package.json
  cla-landing-page/src/app/app-routing.module.ts
  cla-landing-page/src/app/app.component.html
  cla-landing-page/src/app/app.component.scss
  cla-landing-page/src/app/app.component.ts
  cla-landing-page/src/app/app.module.ts
  cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.html
  cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.scss
  cla-landing-page/src/app/components/cla-console-section/cla-console-section.component.ts
  cla-landing-page/src/app/components/cla-footer/cla-footer.component.html
  cla-landing-page/src/app/components/cla-footer/cla-footer.component.ts
  cla-landing-page/src/app/components/page-not-found/page-not-found.component.html
  cla-landing-page/src/app/components/page-not-found/page-not-found.component.scss
  cla-landing-page/src/app/components/page-not-found/page-not-found.component.spec.ts
  cla-landing-page/src/app/components/page-not-found/page-not-found.component.ts
  cla-landing-page/src/app/config/app-settings.ts
  cla-landing-page/src/app/config/auth-utils.ts
  cla-landing-page/src/app/core/services/auth.service.ts
  cla-landing-page/src/environments/environment.dev.ts
  cla-landing-page/src/environments/environment.prod.ts
  cla-landing-page/src/environments/environment.staging.ts
  cla-landing-page/src/environments/environment.ts
Labels: enhancement

#1931 Completed LFX header replacement for corporate console screens
  cla-frontend-corporate-console/edge/security-headers.js
  cla-frontend-corporate-console/src/config/scripts/prefetch-ssm.js
  cla-frontend-corporate-console/src/ionic/app/app.component.ts
  cla-frontend-corporate-console/src/ionic/app/app.scss
  cla-frontend-corporate-console/src/ionic/assets/fonts/Lato-Regular-latin-ext.woff2
  cla-frontend-corporate-console/src/ionic/assets/fonts/Lato-Regular-latin.woff2
  cla-frontend-corporate-console/src/ionic/assets/fonts/Lato/Lato-Regular.ttf
  cla-frontend-corporate-console/src/ionic/assets/fonts/OpenSans-Regular-cyrillic-ext.woff2
  cla-frontend-corporate-console/src/ionic/assets/fonts/OpenSans-Regular-cyrillic.woff2
  cla-frontend-corporate-console/src/ionic/assets/fonts/OpenSans-Regular-greek-ext.woff2
  cla-frontend-corporate-console/src/ionic/assets/fonts/OpenSans-Regular-greek.woff2
  cla-frontend-corporate-console/src/ionic/assets/fonts/OpenSans-Regular-latin-ext.woff2
  cla-frontend-corporate-console/src/ionic/assets/fonts/OpenSans-Regular-latin.woff2
  cla-frontend-corporate-console/src/ionic/assets/fonts/OpenSans-Regular-vietnamese.woff2
  cla-frontend-corporate-console/src/ionic/assets/fonts/Open_Sans/LICENSE.txt
  cla-frontend-corporate-console/src/ionic/assets/fonts/Open_Sans/OpenSans-Regular.ttf
  cla-frontend-corporate-console/src/ionic/assets/fonts/WorkSans-Regular-latin-ext.woff2
  cla-frontend-corporate-console/src/ionic/assets/fonts/WorkSans-Regular-latin.woff2
  cla-frontend-corporate-console/src/ionic/assets/fonts/lato-font.scss
  cla-frontend-corporate-console/src/ionic/assets/fonts/open-sans-font.scss
  cla-frontend-corporate-console/src/ionic/assets/fonts/roboto-light.ttf
  cla-frontend-corporate-console/src/ionic/assets/fonts/work-sans-font.scss
  cla-frontend-corporate-console/src/ionic/decorators/restricted.ts
  cla-frontend-corporate-console/src/ionic/index.html
  cla-frontend-corporate-console/src/ionic/layout/cla-header/cla-header.html
  cla-frontend-corporate-console/src/ionic/layout/cla-header/cla-header.scss
  cla-frontend-corporate-console/src/ionic/layout/cla-header/cla-header.ts
  cla-frontend-corporate-console/src/ionic/layout/layout.module.ts
  cla-frontend-corporate-console/src/ionic/layout/lfx-header/lfx-header.html
  cla-frontend-corporate-console/src/ionic/layout/lfx-header/lfx-header.scss
  cla-frontend-corporate-console/src/ionic/layout/lfx-header/lfx-header.ts
  cla-frontend-corporate-console/src/ionic/pages/auth/auth.ts
  cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.html
  cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.scss
  cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.ts
  cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.html
  cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.scss
  cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.ts
  cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.html
  cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.scss
  cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts
  cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html
  cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.scss
  cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts
  cla-frontend-corporate-console/src/ionic/pages/login-page/login-page.html
  cla-frontend-corporate-console/src/ionic/pages/login-page/login-page.module.ts
  cla-frontend-corporate-console/src/ionic/pages/login-page/login-page.scss
  cla-frontend-corporate-console/src/ionic/pages/login-page/login-page.ts
  cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html
  cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.scss
  cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
  cla-frontend-corporate-console/src/ionic/services/auth.service.ts
  cla-frontend-corporate-console/src/ionic/services/cla.service.ts
Labels: 01 - High, enhancement

#1942 Migrate GitHub organisation API to golang
  cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.html
  cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.scss
  cla-frontend-project-console/src/ionic/modals/cla-configure-github-repositories-modal/cla-configure-github-repositories-modal.ts
  cla-frontend-project-console/src/ionic/modals/cla-gerrit-modal/cla-gerrit-modal.html
  cla-frontend-project-console/src/ionic/modals/cla-gerrit-modal/cla-gerrit-modal.scss
  cla-frontend-project-console/src/ionic/modals/cla-gerrit-modal/cla-gerrit-modal.ts
  cla-frontend-project-console/src/ionic/modals/cla-organization-provider-modal/cla-organization-provider-modal.ts
  cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
  cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
  cla-frontend-project-console/src/ionic/services/cla.service.ts
Labels: 01 - High, Console - Proj, bug

#1943 Updated SSM param landing-page key.
  cla-frontend-corporate-console/src/ionic/decorators/restricted.ts
  cla-frontend-corporate-console/src/ionic/pages/auth/auth.ts
  cla-frontend-corporate-console/src/ionic/services/auth.service.ts
Labels: bug

#1955 Added lfx-header-enabled flag to switch between old and new header
  cla-frontend-corporate-console/src/ionic/app/app.component.ts
  cla-frontend-corporate-console/src/ionic/decorators/restricted.ts
  cla-frontend-corporate-console/src/ionic/layout/cla-header/cla-header.html
  cla-frontend-corporate-console/src/ionic/layout/cla-header/cla-header.scss
  cla-frontend-corporate-console/src/ionic/layout/cla-header/cla-header.ts
  cla-frontend-corporate-console/src/ionic/layout/layout.module.ts
  cla-frontend-corporate-console/src/ionic/pages/auth/auth.ts
  cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.html
  cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.module.ts
  cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.scss
  cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.ts
  cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.html
  cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.module.ts
  cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.scss
  cla-frontend-corporate-console/src/ionic/pages/cla-corporate-page/cla-corporate-page.ts
  cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.html
  cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.module.ts
  cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.scss
  cla-frontend-corporate-console/src/ionic/pages/companies-page/companies-page.ts
  cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.html
  cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.module.ts
  cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.scss
  cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts
  cla-frontend-corporate-console/src/ionic/pages/login-page/login-page.html
  cla-frontend-corporate-console/src/ionic/pages/login-page/login-page.module.ts
  cla-frontend-corporate-console/src/ionic/pages/login-page/login-page.scss
  cla-frontend-corporate-console/src/ionic/pages/login-page/login-page.ts
  cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.html
  cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.module.ts
  cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.scss
  cla-frontend-corporate-console/src/ionic/pages/project-page/project-page.ts
  cla-frontend-corporate-console/src/ionic/services/auth.service.ts
  cla-frontend-corporate-console/src/ionic/services/cla.service.ts
Labels: enhancement

#1964 Added flag based LFX header to Project Console.
  cla-frontend-project-console/edge/security-headers.js
  cla-frontend-project-console/src/config/scripts/prefetch-ssm.js
  cla-frontend-project-console/src/ionic/app/app.component.ts
  cla-frontend-project-console/src/ionic/decorators/restricted.ts
  cla-frontend-project-console/src/ionic/layout/cla-header/cla-header.html
  cla-frontend-project-console/src/ionic/layout/cla-header/cla-header.scss
  cla-frontend-project-console/src/ionic/layout/cla-header/cla-header.ts
  cla-frontend-project-console/src/ionic/layout/layout.module.ts
  cla-frontend-project-console/src/ionic/layout/lfx-header/lfx-header.html
  cla-frontend-project-console/src/ionic/layout/lfx-header/lfx-header.scss
  cla-frontend-project-console/src/ionic/layout/lfx-header/lfx-header.ts
  cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.html
  cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.scss
  cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts
  cla-frontend-project-console/src/ionic/pages/auth/auth.ts
  cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.html
  cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.scss
  cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.ts
  cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
  cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.scss
  cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
  cla-frontend-project-console/src/ionic/services/auth.service.ts
Labels: enhancement

#1944 Generated Template Overwrites Old Template in S3
  cla-frontend-project-console/src/ionic/modals/cla-contract-version-modal/cla-contract-version-modal.ts
  cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
  cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.ts
Labels: bug

#1978 Completed flag based LFX-header implementation
  cla-frontend-contributor-console/src/config/scripts/prefetch-ssm.js
  cla-frontend-contributor-console/src/ionic/app/app.component.ts
  cla-frontend-contributor-console/src/ionic/app/app.scss
  cla-frontend-contributor-console/src/ionic/assets/fonts/Lato-Regular-latin-ext.woff2
  cla-frontend-contributor-console/src/ionic/assets/fonts/Lato-Regular-latin.woff2
  cla-frontend-contributor-console/src/ionic/assets/fonts/Lato/Lato-Regular.ttf
  cla-frontend-contributor-console/src/ionic/assets/fonts/OpenSans-Regular-cyrillic-ext.woff2
  cla-frontend-contributor-console/src/ionic/assets/fonts/OpenSans-Regular-cyrillic.woff2
  cla-frontend-contributor-console/src/ionic/assets/fonts/OpenSans-Regular-greek-ext.woff2
  cla-frontend-contributor-console/src/ionic/assets/fonts/OpenSans-Regular-greek.woff2
  cla-frontend-contributor-console/src/ionic/assets/fonts/OpenSans-Regular-latin-ext.woff2
  cla-frontend-contributor-console/src/ionic/assets/fonts/OpenSans-Regular-latin.woff2
  cla-frontend-contributor-console/src/ionic/assets/fonts/OpenSans-Regular-vietnamese.woff2
  cla-frontend-contributor-console/src/ionic/assets/fonts/Open_Sans/LICENSE.txt
  cla-frontend-contributor-console/src/ionic/assets/fonts/Open_Sans/OpenSans-Regular.ttf
  cla-frontend-contributor-console/src/ionic/assets/fonts/WorkSans-Regular-latin-ext.woff2
  cla-frontend-contributor-console/src/ionic/assets/fonts/WorkSans-Regular-latin.woff2
  cla-frontend-contributor-console/src/ionic/assets/fonts/lato-font.scss
  cla-frontend-contributor-console/src/ionic/assets/fonts/open-sans-font.scss
  cla-frontend-contributor-console/src/ionic/assets/fonts/roboto-light.ttf
  cla-frontend-contributor-console/src/ionic/assets/fonts/work-sans-font.scss
  cla-frontend-contributor-console/src/ionic/layout/cla-header/cla-header.html
  cla-frontend-contributor-console/src/ionic/layout/cla-header/cla-header.scss
  cla-frontend-contributor-console/src/ionic/layout/cla-header/cla-header.ts
  cla-frontend-contributor-console/src/ionic/layout/layout.module.ts
  cla-frontend-contributor-console/src/ionic/layout/lfx-header/lfx-header.html
  cla-frontend-contributor-console/src/ionic/layout/lfx-header/lfx-header.scss
  cla-frontend-contributor-console/src/ionic/layout/lfx-header/lfx-header.ts
  cla-frontend-contributor-console/src/ionic/pages/auth/auth.ts
  cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-confirm/cla-employee-company-confirm.html
  cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-confirm/cla-employee-company-confirm.module.ts
  cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-confirm/cla-employee-company-confirm.scss
  cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-confirm/cla-employee-company-confirm.ts
  cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-troubleshoot/cla-employee-company-troubleshoot.html
  cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-troubleshoot/cla-employee-company-troubleshoot.module.ts
  cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-troubleshoot/cla-employee-company-troubleshoot.scss
  cla-frontend-contributor-console/src/ionic/pages/cla-employee-company-troubleshoot/cla-employee-company-troubleshoot.ts
  cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.html
  cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.module.ts
  cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.scss
  cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-corporate/cla-gerrit-corporate.ts
  cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-individual/cla-gerrit-individual.html
  cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-individual/cla-gerrit-individual.module.ts
  cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-individual/cla-gerrit-individual.scss
  cla-frontend-contributor-console/src/ionic/pages/cla-gerrit-individual/cla-gerrit-individual.ts
  cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.html
  cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.module.ts
  cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.scss
  cla-frontend-contributor-console/src/ionic/pages/cla-individual/cla-individual.ts
  cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.html
  cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.module.ts
  cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.scss
  cla-frontend-contributor-console/src/ionic/pages/cla-landing/cla-landing.ts
  cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.module.ts
  cla-frontend-project-console/src/ionic/pages/project/project-cla-template/project-cla-template.module.ts
  cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.html
  cla-frontend-project-console/src/ionic/pages/project/project-cla/project-cla.module.ts
Labels: enhancement

#2036 Removed v1 basepath from organization service client
  cla-backend-go/v2/organization-service/client.go
Labels: do-not-merge

#2047 Solved issue of Auth0 cookies in project console
  cla-frontend-project-console/edge/security-headers.js
  cla-frontend-project-console/src/ionic/decorators/restricted.ts
  cla-frontend-project-console/src/ionic/pages/all-projects/all-projects.ts
  cla-frontend-project-console/src/ionic/pages/auth/auth.ts
  cla-frontend-project-console/src/ionic/services/auth.service.ts
  cla-landing-page/package.json
  cla-landing-page/src/app/app.component.ts
  cla-landing-page/src/app/app.module.ts
  cla-landing-page/src/app/core/services/auth.service.ts
  cla-landing-page/src/app/core/services/lfx-header.service.spec.ts
  cla-landing-page/src/app/core/services/lfx-header.service.ts
  cla-landing-page/yarn.lock
Labels: bug

#2064 Completed Corporate Console Auth0 implementation and solved minor issues
  cla-frontend-contributor-console/src/ionic/app/app.component.ts
  cla-frontend-corporate-console/src/ionic/layout/cla-header/cla-header.html
  cla-frontend-corporate-console/src/ionic/pages/auth/auth.ts
  cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.html
  cla-frontend-corporate-console/src/ionic/pages/authority-yesno-page/authority-yesno-page.scss
  cla-frontend-corporate-console/src/ionic/services/auth.service.ts
  cla-frontend-project-console/src/ionic/pages/auth/auth.ts
  cla-frontend-project-console/src/ionic/services/auth.service.ts
  cla-landing-page/src/app/core/services/auth.service.ts
  cla-landing-page/src/environments/environment.ts
Labels: bug

#2074 Solved issue of environment not loaded properly
  cla-landing-page/angular.json
Labels: bug

#2086 Replace EasyCLA Footer with the EasyCLA LFX Logo
  cla-frontend-contributor-console/src/ionic/assets/logo/cla-icon-logo.png
  cla-frontend-contributor-console/src/ionic/assets/logo/cp_app_easycla-w.svg
  cla-frontend-contributor-console/src/ionic/assets/logo/cp_app_easycla.svg
  cla-frontend-contributor-console/src/ionic/assets/logo/lfx-easycla.png
  cla-frontend-contributor-console/src/ionic/assets/logo/logo_white.svg
  cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.html
  cla-frontend-corporate-console/src/ionic/assets/img/boat.jpeg
  cla-frontend-corporate-console/src/ionic/assets/img/cb_bg8.jpg
  cla-frontend-corporate-console/src/ionic/assets/img/lf_logo.png
  cla-frontend-corporate-console/src/ionic/assets/logo/cla-icon-logo.png
  cla-frontend-corporate-console/src/ionic/assets/logo/cp_app_easycla-w.svg
  cla-frontend-corporate-console/src/ionic/assets/logo/cp_app_easycla.svg
  cla-frontend-corporate-console/src/ionic/assets/logo/easycla.png
  cla-frontend-corporate-console/src/ionic/assets/logo/lfx-easycla.png
  cla-frontend-corporate-console/src/ionic/assets/logo/logo_white.svg
  cla-frontend-corporate-console/src/ionic/layout/cla-footer/cla-footer.html
  cla-frontend-corporate-console/src/ionic/pages/login-page/login-page.scss
  cla-frontend-project-console/src/ionic/assets/logo/cp_app_easycla-w.svg
  cla-frontend-project-console/src/ionic/assets/logo/cp_app_easycla.svg
  cla-frontend-project-console/src/ionic/assets/logo/lfx-easycla.png
  cla-frontend-project-console/src/ionic/layout/cla-footer/cla-footer.html
  cla-frontend-project-console/src/ionic/pages/login/login.scss
Labels: enhancement

#2090 V1 - Corporate Console - There are duplicate links for Get Help and EasyCLA Documentation
  cla-frontend-contributor-console/src/ionic/constants/general.ts
  cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.html
  cla-frontend-contributor-console/src/ionic/layout/cla-footer/cla-footer.ts
  cla-frontend-contributor-console/src/ionic/layout/cla-header/cla-header.html
  cla-frontend-corporate-console/src/ionic/constant/general.ts
  cla-frontend-corporate-console/src/ionic/layout/cla-footer/cla-footer.html
  cla-frontend-corporate-console/src/ionic/layout/cla-header/cla-header.html
  cla-frontend-project-console/src/ionic/constants/general.ts
  cla-frontend-project-console/src/ionic/layout/cla-footer/cla-footer.html
  cla-frontend-project-console/src/ionic/layout/cla-header/cla-header.html
Labels: bug
